jobs:
  - job: Windows
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run compile'
      - script: 'node node_modules/vscode/bin/test'
        displayName: 'Run tests'
      - task: DotNetCoreInstaller@0
        displayName: 'Use .NET Core sdk 2.1.300'
        inputs:
          version: 2.1.300
      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 4.3.0'
      - task: vsintellinav.vsck-service-endpoint.build-task.upload-cache-build-task@0
        displayName: 'VS IntelliNav Upload'
        inputs:
          vsckEndpoint: 'vscloudkernel-dev'
          nugetpat: 'vscloudkernel-nuget'
          language: typescript
          githubpat: karigari
          nugetVersion: '0.1.806-alpha-g2adb5dd333'
  - job: macOS
    pool:
      name: Hosted macOS
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run compile'
      - script: 'node node_modules/vscode/bin/test'
        displayName: 'Run tests'
  - job: Linux
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run compile'
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: 'Start xvfb'
      - script: 'node node_modules/vscode/bin/test'
        displayName: 'Run tests'
        env:
          DISPLAY: :10